Portfolio/Models/ErrorViewModel.cs
namespace Portfolio.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Portfolio/Areas/AdminPanel/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Portfolio.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class DashBoardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Portfolio/Areas/AdminPanel/Controllers/SkillController.cs
using Microsoft.AspNetCore.Mvc;
using Portfolio.Business.Services.Interfaces;

namespace Portfolio.Areas.AdminPanel.Controllers
{    
    [Area("AdminPanel")]
    public class SkillController : Controller
    {
        private readonly IUnitOfWorkService _unitOfWorkService;

        public SkillController(IUnitOfWorkService unitOfWorkService)
        {
            _unitOfWorkService = unitOfWorkService;
        }

        public async Task< ActionResult> Index()
        {
            return View(await _unitOfWorkService.SkillService.GetAllAsync());
        }

        // // GET: SkillController/Details/5
        // public ActionResult Details(int id)
        // {
        //     return View();
        // }

        // GET: SkillController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SkillController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormFile Icon)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // // GET: SkillController/Edit/5
        // public ActionResult Edit(int id)
        // {
        //     return View();
        // }

        // POST: SkillController/Edit/5
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public ActionResult Edit(int id, IFormCollection collection)
        // {
        //     try
        //     {
        //         return RedirectToAction(nameof(Index));
        //     }
        //     catch
        //     {
        //         return View();
        //     }
        // }
        //
        // // GET: SkillController/Delete/5
        // public ActionResult Delete(int id)
        // {
        //     return View();
        // }

        // // POST: SkillController/Delete/5
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public ActionResult Delete(int id, IFormCollection collection)
        // {
        //     try
        //     {
        //         return RedirectToAction(nameof(Index));
        //     }
        //     catch
        //     {
        //         return View();
        //     }
        // }
    }
}

Portfolio/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Portfolio.Models;
using System.Diagnostics;

namespace Portfolio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Portfolio/Areas/AdminPanel/Views/DashBoard/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Portfolio/Areas/AdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8"/>
    <title>Station Baku Restaurant</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Responsive bootstrap 4 admin template" name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/Admin/assets/images/favicon.ico">

    <!-- Plugins css-->
    <link href="~/Admin/assets/libs/sweetalert2/sweetalert2.min.css" rel="stylesheet" type="text/css"/>

    <!-- App css -->
    <link href="~/Admin/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" id="bootstrap-stylesheet"/>
    <link href="~/Admin/assets/css/icons.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/Admin/assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-stylesheet"/>

</head>

<body>

<!-- Begin page -->
<div id="wrapper">


<!-- Topbar Start -->
<div class="navbar-custom">
<ul class="list-unstyled topnav-menu float-right mb-0">

<li class="dropdown notification-list">
    <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
        @* <img src="~/Admin/assets/images/users/avatar-1.jpg" alt="user-image" class="rounded-circle"> *@
        <h4 class="pro-user-name ml-1">
            @if (User.Identity.IsAuthenticated)
            {
                @User.Identity.Name
            }


          @*  else
            {
                <a asp-controller="Account" asp-action="Login" asp-route-ReturnUrl="@Context.Request.Path.Value">Login</a>
            }*@
            <i class="ion ion-ios-arrow-down"></i>
        </h4>
    </a>
    <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
        <!-- item-->
        <div class="dropdown-header noti-title">
            <h6 class="text-overflow m-0">Welcome !</h6>
        </div>

        @* <!-- item--> *@
        @* <a href="javascript:void(0);" class="dropdown-item notify-item"> *@
        @*     <i class="mdi mdi-account-outline"></i> *@
        @*     <span>Profile</span> *@
        @* </a> *@
        @* *@
        @* <!-- item--> *@
        @* <a href="javascript:void(0);" class="dropdown-item notify-item"> *@
        @*     <i class="mdi mdi-settings-outline"></i> *@
        @*     <span>Settings</span> *@
        @* </a> *@

        

        <div class="dropdown-divider"></div>

        <!-- item-->
     @* @todo *@
        @* <a asp-area="" asp-controller="Account" asp-action="Logout" class="dropdown-item notify-item"> *@
        @*     <i class="mdi mdi-logout-variant"></i> *@
        @*     <span>Logout</span> *@
        @* </a> *@

    </div>
</li>

@* <li class="dropdown notification-list"> *@
@*     <a href="javascript:void(0);" class="nav-link right-bar-toggle waves-effect"> *@
@*         <i class="mdi mdi-settings-outline noti-icon"></i> *@
@*     </a> *@
@* </li> *@


</ul>

<!-- LOGO -->
<div class="logo-box">
    <a asp-controller="DashBoard" asp-action="Index" class="logo text-center logo-dark">
        <span class="logo-lg">
            <span class="logo-lg-text-light">Admin</span>
        </span>
        <span class="logo-sm">
            <span class="logo-lg-text-light">Admin</span>
        </span>
    </a>

    <a asp-controller="DashBoard" asp-action="Index" class="logo text-center logo-light">
        <span class="logo-lg">
            <span class="logo-lg-text-light">Admin</span>
        </span>
        <span class="logo-sm">
            <span class="logo-lg-text-light">Admin</span>
        </span>
    </a>
</div>

<!-- LOGO -->


<ul class="list-unstyled topnav-menu topnav-menu-left m-0">
    <li>
        <button class="button-menu-mobile waves-effect">
            <i class="mdi mdi-menu"></i>
        </button>
    </li>


    <li class="d-none d-lg-block">
        <form class="app-search">
            <div class="app-search-box">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search...">
                    <div class="input-group-append">
                        <button class="btn" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </li>
</ul>
</div>
<!-- end Topbar --> <!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">

    <div class="slimscroll-menu">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <ul class="metismenu" id="side-menu">

                <li class="menu-title">Navigation</li>

                <li>
                    <a asp-area="AdminPanel" asp-controller="DashBoard" asp-action="Index" class="waves-effect">
                        <i class=" fas fa-compass"></i>
                        <span class="text-light">DashBoard </span>
                    </a>
                </li>
                <li>
                    <a asp-area="AdminPanel" asp-controller="Skill" asp-action="Index" class="waves-effect">
                        <i class=" fas fa-compass"></i>
                        <span class="text-light">Skills</span>
                    </a>
                </li> 
                @* <li> *@
                @*     <a asp-area="AdminRezerv" asp-controller="Category" asp-action="Index" class="waves-effect"> *@
                @*         <i class=" fab fa-slack-hash"></i> *@
                @*         <span class="text-light">Product Category </span> *@
                @*     </a> *@
                @* </li> *@
                @* <li> *@
                @*     <a asp-area="AdminRezerv" asp-controller="Product" asp-action="Index" class="waves-effect"> *@
                @*         <i class="mdi mdi-food"></i> *@
                @*         <span class="text-light">Products</span> *@
                @*     </a> *@
                @* </li> *@
                @* <li> *@
                @*     <a asp-area="AdminRezerv" asp-controller="Table" asp-action="Index" class="waves-effect"> *@
                @*         <i class="  fas fa-table"></i> *@
                @*         <span class="text-light">Tables</span> *@
                @*     </a> *@
                @* </li> *@
                @* <li> *@
                @*     <a asp-area="AdminRezerv" asp-controller="Reservation" asp-action="Index" class="waves-effect"> *@
                @*         <i class="  fas fa-save"></i> *@
                @*         <span class="text-light">Reservations</span> *@
                @*     </a> *@
                @* </li> *@
                @* <li> *@
                @*     <a asp-area="AdminRezerv" asp-controller="Gallery" asp-action="Index" class="waves-effect"> *@
                @*         <i class=" ion ion-md-images"></i> *@
                @*         <span class="text-light">Gallery</span> *@
                @*     </a> *@
                @* </li> *@
                @* <li> *@
                @*     <a asp-area="AdminRezerv" asp-controller="Contact" asp-action="Index" class="waves-effect"> *@
                @*         <i class=" far fa-address-book"></i> *@
                @*         <span class="text-light">Contact</span> *@
                @*     </a> *@
                @* </li> *@
                @* <li> *@
                @*     <a asp-area="AdminRezerv" asp-controller="Message" asp-action="Index" class="waves-effect"> *@
                @*         <i class=" far fa-paper-plane"></i> *@
                @*         <span class="text-light">Send Notification</span> *@
                @*     </a> *@
                @* </li> *@
                @* <li> *@
                @*     <a asp-area="" asp-controller="Account" asp-action="Create" class="waves-effect"> *@
                @*         <i class=" fas fa-user-plus"></i> *@
                @*         <span class="text-light">Admin Register</span> *@
                @*     </a> *@
                @* </li> *@
                @* <li> *@
                @*     <a href="javascript: void(0);" class="waves-effect"> *@
                @*         <i class="mdi mdi-settings-outline"></i> *@
                @*         <span class="text-light">Setting</span> *@
                @*     </a> *@
                @*     <ul class="nav-second-level" aria-expanded="false"> *@
                @*         <li> *@
                @*             <a asp-controller="HeadSlide" asp-action="Index">Head Slider</a> *@
                @*         </li> *@
                @*         <li> *@
                @*             <a asp-controller="Setting" asp-action="Index">Plan And Parallax</a> *@
                @*         </li> *@
                @*         <li> *@
                @*             <a asp-controller="About" asp-action="Index">About </a> *@
                @*         </li> *@
                @* *@
                @*     </ul> *@
                @* </li> *@

            </ul>

        </div>
        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->
@RenderBody()
<!-- Right Sidebar -->
<div class="right-bar">
    <div class="rightbar-title">
        <a href="javascript:void(0);" class="right-bar-toggle float-right">
            <i class="mdi mdi-close"></i>
        </a>
        <h4 class="font-17 m-0 text-white">Theme Customizer</h4>
    </div>
    <div class="slimscroll-menu">

        <div class="p-4">
            <div class="alert alert-warning" role="alert">
                <strong>Customize </strong> the overall color scheme, layout, etc.
            </div>
            <div class="mb-2">
                <img src="~/Admin/assets/images/layouts/light.png" class="img-fluid img-thumbnail" alt="">
            </div>
            <div class="custom-control custom-switch mb-3">
                <input type="checkbox" class="custom-control-input theme-choice" id="light-mode-switch" checked/>
                <label class="custom-control-label" for="light-mode-switch">Light Mode</label>
            </div>

            <div class="mb-2">
                <img src="~/Admin/assets/images/layouts/dark.png" class="img-fluid img-thumbnail" alt="">
            </div>
            <div class="custom-control custom-switch mb-3">
                <input type="checkbox" class="custom-control-input theme-choice" id="dark-mode-switch" data-bsStyle="~/Admin/assets/css/bootstrap-dark.min.css"
                       data-appStyle="~/Admin/assets/css/app-dark.min.css"/>
                <label class="custom-control-label" for="dark-mode-switch">Dark Mode</label>
            </div>

            <div class="mb-2">
                <img src="~/Admin/assets/images/layouts/rtl.png" class="img-fluid img-thumbnail" alt="">
            </div>
            <div class="custom-control custom-switch mb-5">
                <input type="checkbox" class="custom-control-input theme-choice" id="rtl-mode-switch" data-appStyle="~/Admin/assets/css/app-rtl.min.css"/>
                <label class="custom-control-label" for="rtl-mode-switch">RTL Mode</label>
            </div>

        </div>
    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->
<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>


<!-- Vendor js -->
<script src="~/Admin/assets/js/vendor.min.js"></script>

<script src="~/Admin/assets/libs/moment/moment.min.js"></script>
<script src="~/Admin/assets/libs/jquery-scrollto/jquery.scrollTo.min.js"></script>
<script src="~/Admin/assets/libs/sweetalert2/sweetalert2.min.js"></script>

<!-- Chat app -->
<script src="~/Admin/assets/js/pages/jquery.chat.js"></script>

<!-- Todo app -->
<script src="~/Admin/assets/js/pages/jquery.todo.js"></script>

<!--Morris Chart-->
<script src="~/Admin/assets/libs/morris-js/morris.min.js"></script>
<script src="~/Admin/assets/libs/raphael/raphael.min.js"></script>

<!-- Sparkline charts -->
<script src="~/Admin/assets/libs/jquery-sparkline/jquery.sparkline.min.js"></script>

<!-- Dashboard init JS -->
<script src="~/Admin/assets/js/pages/dashboard.init.js"></script>

<!-- App js -->
<script src="~/Admin/assets/js/app.min.js"></script>
@RenderSection("scripts",false)
</div>

</body>

</html>

Portfolio/Areas/AdminPanel/Views/Skill/Create.cshtml
@model IFormFile
<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <h4 class="page-title">Slide Image</h4>
                        <div class="page-title-right">
                            <ol class="breadcrumb p-0 m-0">
                                <li class="breadcrumb-item">
                                    <a href="#">Velonic</a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a href="#">Forms</a>
                                </li>
                                <li class="breadcrumb-item active">Form Validation</li>
                            </ol>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title mb-4">Basic Form</h4>

                            <form class="parsley-examples" method="post" enctype="multipart/form-data">
                                <div class="form-group">
                                    @* <div class="text-danger" asp-validation-summary="All"></div> *@
                                    
                                    <label  name="Icon">Icon<span class="text-danger">*</span> </label>
                                    <input name="Icon" parsley-trigger="change" required  type="file"  class="form-control">
                                    <span class="text-danger" name="Icon"></span>
                                </div>
                             
                                <div class="form-group text-right mb-0">
                                    <button class="btn btn-primary waves-effect waves-light mr-1" type="submit">
                                        Submit
                                    </button>
                                    <button type="reset" class="btn btn-secondary waves-effect waves-light">
                                        Cancel
                                    </button>
                                </div>

                            </form>
                        </div>
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->

            </div>

        </div>
        <!-- end container-fluid -->

    </div>
    <!-- end content -->


    <!-- Footer Start -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    2015 - 2022 &copy; Velonic theme by <a href="#">Coderthemes</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- end Footer -->

</div>

Portfolio/Areas/AdminPanel/Views/Skill/Index.cshtml
@model List<Skill>
@{
    int count = 1;
}
 
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body table-responsive">
                            <h4 class="m-t-0 header-title mb-4">
                                <b>Skills</b>
                            </h4>
                            <a class="btn btn-info waves-effect width-md waves-light mb-3 " asp-action="Create" style="color:#ffffff  ">Add</a>
                            <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">

                                <thead>
                                    <tr>
                                        <th>№</th>
                                        <th>Image</th>
                                        <th>Update Date</th>
                                        <th>Setting</th>

                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (Skill skill in Model)
                                    {
                                        <tr>
                                            <td>@count </td>
                                            <td>
                                                <a href="~/Assets/img/@skill.Icon">
                                                    <img src="~/Assets/img/@skill.Icon" width="70" class="img-fluid" alt="">
                                                </a>
                                            </td>
                                            @* <td>@TimeZoneInfo.ConvertTimeBySystemTimeZoneId(product.CreatedAt, "W. Europe Standard Time"); </td> *@
                                            <td>@TimeZoneInfo.ConvertTime(skill.UpdatedAt, TimeZoneInfo.FindSystemTimeZoneById("Central Standard Time")); </td>

                                            @* <td> *@
                                            @*     <a class="btn btn-icon waves-effect waves-light btn-purple" asp-action="Update" asp-route-id="@product.Id"> *@
                                            @*         <i class="mdi mdi-pencil-outline"></i> *@
                                            @*     </a> *@
                                            @*     <a class="btn btn-icon waves-effect waves-light btn-danger" asp-action="Delete" asp-route-id="@product.Id"> *@
                                            @*         <i class="mdi mdi-delete-outline"></i> *@
                                            @*     </a> *@
                                            @* </td> *@

                                        </tr>


                                        count++;
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- end container-fluid -->

    </div>
    <!-- end content -->
    <!-- Footer Start -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    2015 - 2022 &copy; Velonic theme by <a href="#">Coderthemes</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- end Footer -->

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

Portfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Javid Hajiyev">
    <meta name="keyword" content="web,developer,portfolio">
    <meta name="description" content="Javid Hajiyev is 2+ year experienced Software Developer.">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="icon/svg" href="~/Assets/img/Javid Haciyev-Gradient.svg">
    <!--Box Icon CDn-->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!--Slick Carousel CDN-->
    <link rel="stylesheet" type="text/css" href="~/Assets/slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="~/Assets/slick/slick-theme.css" />
    <!--CSS Import-->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="~/Assets/styles/style.min.css">
    <title>Javid Hajiyev | Software Developer</title>
</head>
<body>
    <header class="header" id="header">
        <nav class="navbar container">
            <div class="logo">
                <a href=""><img src="~/Assets/img/Javid Haciyev-White.svg" alt="Faril Mammadov"></a>
            </div>
            <ul class="nav__main">
                <li class="nav__item"><a href="#home" class="nav__link">Home</a></li>
                <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                <li class="nav__item"><a href="#resume" class="nav__link">Resume</a></li>
                <li class="nav__item"><a href="#portfolio" class="nav__link">Portfolio</a></li>
                <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
            </ul>
            <div class="nav__btn">
                <div class="donate__btn">
                    <button>Donate Me</button>
                </div>
                <div class="nav__menu">
                    <i class='bx bx-menu'></i>
                </div>
            </div>
        </nav>
    </header>

    <div class="scroll__btn">
        <i class='bx bx-up-arrow-alt'></i>
    </div>

    <div class="mobile__menu">
        <div class="mobile__nav container">
            <div class="nav__top">
                <div class="mobile-logo">
                    <img src="~/Assets/img/Javid Haciyev-White.svg" alt="">
                </div>
                <div class="close__menu">
                    <i class='bx bx-x'></i>
                </div>
            </div>
            <div class="nav__main">
                <ul class="nav__list">
                    <li class="nav__item"><a href="#home" class="nav__link">Home</a></li>
                    <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                    <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                    <li class="nav__item"><a href="#resume" class="nav__link">Resume</a></li>
                    <li class="nav__item"><a href="#portfolio" class="nav__link">Portfolio</a></li>
                    <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="shape-1">
        <img src="~/Assets/img/shapes.svg" alt="">
    </div>
    <div class="shape-2">
        <img src="~/Assets/img/shapes.svg" alt="">
    </div>
    <div class="social__media">
        <a href=""><i class='bx bxl-github'></i></a>
        <a href=""><i class='bx bxl-instagram'></i></a>
        <a href=""><i class='bx bxl-behance'></i></a>
        <a href=""><i class='bx bxl-twitter'></i></a>
        <a href=""><i class='bx bxl-linkedin-square'></i></a>
    </div>
    <div class="ellipse__effect"></div>
    <div class="ellipse__effect-2"></div>
    <!--MAIN SECTION-->
    <main>
            @RenderBody()
        </main>
        <footer>
            <div class="footer__main container">
                <div class="footer__left">
                    <div class="footer__logo">
                        <a href=""><img src="~/Assets/img/Javid Haciyev-White.svg" alt=""></a>
                    </div>
                    <div class="footer__copyright">
                        <p>
                            © 2022 Javid Hajiyev.
                            All rights reserved.
                        </p>
                    </div>
                    <div class="footer__social">
                        <a href=""><i class='bx bxl-github'></i></a>
                        <a href=""><i class='bx bxl-instagram'></i></a>
                        <a href=""><i class='bx bxl-behance'></i></a>
                        <a href=""><i class='bx bxl-twitter'></i></a>
                        <a href=""><i class='bx bxl-linkedin-square'></i></a>
                    </div>
                </div>
                <div class="footer__center">
                    <div class="list__header">
                        <h2>Learn More</h2>
                    </div>
                    <ul class="footer__nav">
                        <li class="nav__item"><a href="#home" class="nav__link">Home</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                        <li class="nav__item"><a href="#resume" class="nav__link">Resume</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Portfolio</a></li>
                        <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                    </ul>
                </div>
                <div class="footer__right">
                    <div class="contact__header">
                        <h2>Contact with me</h2>
                    </div>
                    <div class="contact__info">
                        <p class="email">contact@javidhc.com</p>
                        <p class="phone">+994 77 514 26 44</p>
                        <p class="adress">
                            Azerbaijan , Baku , Khalglar district
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!--Jquery CDN-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <!--Slick Carousel CDN-->
        <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="~/Assets/slick/slick.min.js"></script>
        <!--AOS CDN-->
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
        <script src="~/Assets/scripts/app.js"></script>
</body>
</html>